/// Guards `docs/wiki/REFERENCE.md` the same way `content_export_test.dart`
/// guards `content.json` (ITEMS §10.1, ENEMIES §1.2, designer ask
/// 2026-08-20): the JSON is machine food, this is what a designer actually
/// reads, and both are generated by walking the same catalogues so neither
/// can quietly fall behind the other.
///
/// ⭐ **Mutation-shaped, not just shape-shaped.** Every reverse-index test
/// below names a mutant it is written to kill, per the task brief: a scan
/// that only walks the first zone's items, and a filter that leaks
/// zero-valued fields into a table that promises only nonzero ones.
library;

import 'package:flutter_test/flutter_test.dart';
import 'package:masters_of_magic_2/game/content_export.dart';
import 'package:masters_of_magic_2/game/content_reference.dart';

void main() {
  final counts = ContentExport.build()['counts']! as Map<String, Object?>;
  final markdown = ContentReference.build(counts);

  /// The text from a `### heading` (inclusive) up to the next `##`-or-`###`
  /// heading, so a test can assert something is true of ONE field's table
  /// without a substring match anywhere else in the document accidentally
  /// making it pass.
  String section(String heading) {
    final start = markdown.indexOf(heading);
    expect(
      start,
      greaterThanOrEqualTo(0),
      reason: '"$heading" is missing from REFERENCE.md entirely',
    );
    final next = markdown.indexOf('\n##', start + heading.length);
    return next == -1
        ? markdown.substring(start)
        : markdown.substring(start, next);
  }

  test('regenerating from the same counts is byte-identical', () {
    // ⚠️ Mirrors content_export_test's own determinism check: two builds
    // from the same inputs must encode identically, or every regeneration
    // is diff noise instead of a real content change.
    expect(ContentReference.build(counts), markdown);
  });

  test('the header names the real regenerate command', () {
    expect(
      ContentReference.regenerateCommand,
      'flutter test tool/export_content_test.dart',
    );
    expect(markdown, contains(ContentReference.regenerateCommand));
    expect(markdown, contains('do not edit'));
  });

  test(
    'the counts summary is the SAME map content.json carries, not a recount',
    () {
      // ⭐ ContentReference.build takes `counts` as a parameter precisely so
      // this cannot drift; assert the values that were handed in are the ones
      // that came out.
      expect(
        markdown,
        contains(
          '| ${counts['zones']} | ${counts['towns']} | '
          '${counts['creatures']} | ${counts['items']} | ${counts['recipes']} '
          '| ${counts['gatherNodes']} |',
        ),
      );
    },
  );

  group('reverse stat index', () {
    test('an item from the LAST zone scanned still appears', () {
      // ⭐ accuracyBonus is granted by items in whispering_woods (the FIRST
      // zone in World.locations) and by birch_wand in ashfall_vale (the
      // LAST of the five zones with a catalogue). A mutant that stops after
      // the first zone — or that reads `ItemCatalogue.byZone.values.first`
      // instead of `ItemCatalogue.all` — would pass every check that only
      // looks at whispering_woods and silently drop this row.
      final s = section('### `accuracyBonus`');
      expect(
        s,
        contains('`birch_wand`'),
        reason:
            'birch_wand (ashfall_vale, the last zone) is missing from '
            'the accuracyBonus table — the scan is not walking every zone',
      );
      expect(
        s,
        contains('`oak_circlet`'),
        reason:
            'oak_circlet (whispering_woods, the first zone) should '
            'still be here too',
      );
    });

    test('a field no item carries lists no table and no zero-valued rows', () {
      // ⭐ Nothing in the current catalogue grants dodge, deflectChance or
      // deflectAmount. A mutant that drops the `getter(m) != 0` filter would
      // list EVERY piece of equipment under EVERY field — including these —
      // each row reading a modifier value of 0.
      expect(
        markdown,
        isNot(contains('### `dodge`')),
        reason:
            'no item grants dodge; a `### `dodge`` header means the '
            'zero-value filter broke and equipment with dodge: 0 leaked in',
      );
      expect(markdown, isNot(contains('### `deflectChance`')));
      expect(markdown, isNot(contains('### `deflectAmount`')));
      final noGrants = section('### No item grants');
      expect(noGrants, contains('`dodge`'));
      expect(noGrants, contains('`deflectChance`'));
      expect(noGrants, contains('`deflectAmount`'));
    });

    test('a populated field never lists a row with value 0', () {
      // Same mutant, phrased the other way: within a table that DOES exist,
      // no row's Value column may read 0 — every listed item must be there
      // because it actually carries the stat.
      final s = section('### `maxHpBonus`');
      final rows = s
          .split('\n')
          .where((l) => l.startsWith('| ') && l.contains('`'))
          .skip(1); // header separator row
      for (final row in rows) {
        final cells = row.split('|').map((c) => c.trim()).toList();
        // cells: ['', Name, Id, Value, Slot, Rarity, EquipLv, Zone, '']
        expect(
          cells[3],
          isNot('0'),
          reason: 'row "$row" claims maxHpBonus but lists value 0',
        );
      }
    });

    test(
      'values are the DEF\'s base numbers, with a note that quality scales them',
      () {
        expect(markdown, contains("base numbers"));
        expect(markdown, contains('80/100/120/140%'));
      },
    );
  });

  group('items by zone', () {
    test('every zone with a catalogue gets a section, in shipped order', () {
      final woods = markdown.indexOf('### Whispering Woods');
      final ashfall = markdown.indexOf('### Ashfall Vale (`ashfall_vale`)');
      expect(woods, greaterThanOrEqualTo(0));
      expect(
        ashfall,
        greaterThan(woods),
        reason:
            'Ashfall Vale (a later zone) must be printed after '
            'Whispering Woods (the first) — zone order must follow '
            'World.locations, the shipped order',
      );
    });

    test('row counts per zone sum to the total items count', () {
      final matches = RegExp(r'— (\d+) items').allMatches(markdown);
      final sum = matches.fold<int>(0, (s, m) => s + int.parse(m.group(1)!));
      expect(
        sum,
        counts['items'],
        reason:
            'a zone silently skipped in "Items by zone" would make '
            'this sum fall short of the real item count',
      );
    });

    test(
      'obtained-by is derived from the real recipe, gather and drop tables',
      () {
        // ⭐ Three concrete, independently-verifiable examples — not a
        // re-implementation of _obtainedBy, so this cannot pass by agreeing
        // with a copy of its own bug.
        //
        // ⚠️ Matched by "`id` | Name" (the Items-by-zone column order) rather
        // than by id alone: the SAME id also appears as "Name | `id`" in the
        // reverse stat index above, and indexOf would find that row first.
        expect(markdown, contains('| `oak_log` | Oak Log |'));
        expect(
          markdown
              .substring(markdown.indexOf('| `oak_log` | Oak Log |'))
              .split('\n')
              .first,
          contains('gather: `ww_oak_stand`'),
          reason: 'oak_log is yielded by the ww_oak_stand gather node',
        );
        expect(
          markdown
              .substring(markdown.indexOf('| `oak_circlet` | Oak Circlet |'))
              .split('\n')
              .first,
          contains('drop: `rootknuckle`'),
          reason: 'oak_circlet drops from rootknuckle in the Woods bestiary',
        );
        expect(
          markdown
              .substring(
                markdown.indexOf('| `bindweed_boots` | Bindweed Boots |'),
              )
              .split('\n')
              .first,
          contains('craft: `craft_bindweed_boots`'),
          reason: 'bindweed_boots is craft_bindweed_boots\'s recipe output',
        );
      },
    );
  });

  group('bestiary by zone', () {
    test('every zone with a bestiary gets a section, in shipped order', () {
      final woods = markdown.indexOf(
        '### Whispering Woods (`whispering_woods`) — 11 creatures',
      );
      final ashfall = markdown.indexOf(
        '### Ashfall Vale (`ashfall_vale`) — 11 creatures',
      );
      expect(woods, greaterThanOrEqualTo(0));
      expect(ashfall, greaterThan(woods));
    });

    test(
      'notable drops read the main/bonus tables, never the always table',
      () {
        // ⭐ listening_fawn's `always` bucket guarantees flora_dust on every
        // kill (see whispering_woods.dart's `_commonAlways`), but the task
        // asks only for main/bonus. A mutant that also walks `always` would
        // flood every creature's row with the same mote and this test would
        // catch it on the one creature whose ENTIRE always contribution is
        // that mote.
        final row = markdown
            .substring(markdown.indexOf('| `listening_fawn` |'))
            .split('\n')
            .first;
        expect(
          row,
          isNot(contains('Flora Dust')),
          reason:
              'Flora Dust is an `always` drop for listening_fawn, not '
              'main/bonus — it must not appear in notable drops',
        );
        expect(
          row,
          contains("Forager's Ration"),
          reason:
              "Forager's Ration IS one of listening_fawn's main/bonus "
              'drops and must appear',
        );
      },
    );
  });

  group('recipes by skill', () {
    test('XP is computed by the shipped formula, not re-typed', () {
      // 📝 The worked examples pinned in skills.dart's own doc comment:
      // Oak Quarterstaff (3 logs, gate 1) -> 18; Oak Wand (2 logs, gate 1)
      // -> 12.
      final quarterstaff = markdown
          .substring(markdown.indexOf('| `craft_oak_quarterstaff` |'))
          .split('\n')
          .first;
      expect(quarterstaff, contains('| 18 |'));
      final wand = markdown
          .substring(markdown.indexOf('| `craft_oak_wand` |'))
          .split('\n')
          .first;
      expect(wand, contains('| 12 |'));
    });

    test('every recipe-bearing skill gets its own section', () {
      expect(markdown, contains('### Woodcarving'));
      expect(markdown, contains('### Tailoring'));
      expect(markdown, contains('### Potions & Alchemy'));
    });
  });
}
