/// The human-readable sibling of [ContentExport] — same facts, rendered as
/// Markdown a designer can `Cmd-F` instead of a JSON blob a script can parse.
///
/// ⭐ **A SECOND GENERATED OUTPUT of the same pipeline, never a second
/// truth.** Every table below is built by walking the exact catalogues
/// [ContentExport] walks (`Bestiary`, `ItemCatalogue`, `RecipeBook`,
/// `GatherNodes`, `World`) — never by parsing `content.json` back apart and
/// never by re-typing a number a designer read off a screen. The one
/// exception is the counts summary, which is handed in by the caller so it
/// is *literally* the same map `content.json` carries, not a second formula
/// that could drift from it (see [build]).
///
/// ⚠️ **Do not hand-edit `docs/wiki/REFERENCE.md`.** It is regenerated by
/// `tool/export_content_test.dart` alongside `content.json`; anything typed
/// directly into the file is erased by the next `flutter test
/// tool/export_content_test.dart`.
///
/// ⭐ **The reverse stat index is the headline feature** (designer ask,
/// 2026-08-20): "what items already grant % shield" used to mean grepping
/// five catalogue files by hand. [_reverseStatIndex] answers it as one table
/// per [ItemModifiers] field, built by scanning every item once.
library;

import 'enemies/bestiary.dart';
import 'enemies/drop_table.dart';
import 'enemies/enemy_def.dart';
import 'gathering/gather_node.dart';
import 'items/item_catalogue.dart';
import 'items/item_def.dart';
import 'items/recipe_book.dart';
import 'skills.dart';
import 'world.dart';

abstract final class ContentReference {
  /// The command the header points readers at — kept as one constant so the
  /// doc comment, the emitted warning, and `docs/CONTENT_EXPORT.md` cannot
  /// name three different paths for the same test.
  static const String regenerateCommand =
      'flutter test tool/export_content_test.dart';

  /// Builds the whole Markdown document.
  ///
  /// [counts] is `ContentExport.build()['counts']` — passed in rather than
  /// recomputed so the summary at the top of this file and the summary at
  /// the top of `content.json` are the *same object*, not two formulas that
  /// happen to agree today.
  static String build(Map<String, Object?> counts) {
    final buf = StringBuffer();
    buf.writeln(_header());
    buf.writeln(_countsSummary(counts));
    buf.writeln(_contents());
    buf.writeln(_reverseStatIndex());
    buf.writeln(_itemsByZone());
    buf.writeln(_bestiaryByZone());
    buf.writeln(_recipesBySkill());
    return buf.toString();
  }

  // ---- header -------------------------------------------------------------

  static String _header() =>
      '''
# Masters of Magic 2 — Item & Bestiary Reference

⚠️ **GENERATED from code by the content export — do not edit.** Regenerate
both this file and `docs/wiki/content.json` with:

```
$regenerateCommand
```

Source of truth: [`lib/game/content_export.dart`](../../lib/game/content_export.dart)
builds `content.json`; [`lib/game/content_reference.dart`](../../lib/game/content_reference.dart)
builds this file from the same catalogues. See `docs/CONTENT_EXPORT.md` for
the framework both live under.
''';

  // ---- counts ---------------------------------------------------------------

  static String _countsSummary(Map<String, Object?> counts) {
    final buf = StringBuffer()..writeln('## Counts\n');
    buf.writeln(
      '| Zones | Towns | Creatures | Items | Recipes | Gather nodes |',
    );
    buf.writeln('|---|---|---|---|---|---|');
    buf.writeln(
      '| ${counts['zones']} | ${counts['towns']} | ${counts['creatures']} '
      '| ${counts['items']} | ${counts['recipes']} | ${counts['gatherNodes']} |',
    );
    return buf.toString();
  }

  static String _contents() {
    final buf = StringBuffer()..writeln('## Contents\n');
    buf.writeln('- [Reverse stat index](#reverse-stat-index)');
    buf.writeln('- [Items by zone](#items-by-zone)');
    buf.writeln('- [Bestiary by zone](#bestiary-by-zone)');
    buf.writeln('- [Recipes by skill](#recipes-by-skill)');
    return buf.toString();
  }

  // ---- reverse stat index ---------------------------------------------------

  /// Every [ItemModifiers] field, in the order it is declared on the class —
  /// the same order [ContentExport] emits them, so the two documents read as
  /// one vocabulary rather than two orderings of it.
  static const List<(String, int Function(ItemModifiers))> _modifierFields = [
    ('accuracyBonus', _accuracyBonus),
    ('dodge', _dodge),
    ('critChance', _critChance),
    ('critDamage', _critDamage),
    ('deflectChance', _deflectChance),
    ('deflectAmount', _deflectAmount),
    ('maxHpBonus', _maxHpBonus),
    ('damagePerCast', _damagePerCast),
    ('damagePerCharge', _damagePerCharge),
    ('shieldStrengthPercent', _shieldStrengthPercent),
    ('healingReceivedPercent', _healingReceivedPercent),
    ('regrowPercent', _regrowPercent),
    ('beltSlots', _beltSlots),
  ];

  static int _accuracyBonus(ItemModifiers m) => m.accuracyBonus;
  static int _dodge(ItemModifiers m) => m.dodge;
  static int _critChance(ItemModifiers m) => m.critChance;
  static int _critDamage(ItemModifiers m) => m.critDamage;
  static int _deflectChance(ItemModifiers m) => m.deflectChance;
  static int _deflectAmount(ItemModifiers m) => m.deflectAmount;
  static int _maxHpBonus(ItemModifiers m) => m.maxHpBonus;
  static int _damagePerCast(ItemModifiers m) => m.damagePerCast;
  static int _damagePerCharge(ItemModifiers m) => m.damagePerCharge;
  static int _shieldStrengthPercent(ItemModifiers m) => m.shieldStrengthPercent;
  static int _healingReceivedPercent(ItemModifiers m) =>
      m.healingReceivedPercent;
  static int _regrowPercent(ItemModifiers m) => m.regrowPercent;
  static int _beltSlots(ItemModifiers m) => m.beltSlots;

  /// The [ItemModifiers] an item carries, or null if its kind cannot carry
  /// any (ITEMS §4 grants modifiers to worn Equipment and socketed Gems
  /// only — a Material or a Mote has no stat line to scan).
  static ItemModifiers? _modifiersOf(ItemDef d) => switch (d) {
    EquipmentDef() => d.modifiers,
    GemDef() => d.modifiers,
    _ => null,
  };

  /// ⭐ **Walks every item in [ItemCatalogue.all] once per field** — the
  /// mutant that scans only the first zone's list, or only
  /// `WhisperingWoodsItems`, produces a table that is short by construction
  /// and `test/content_reference_test.dart` catches it by name (an Ashfall
  /// item with a real stat that must appear here).
  static String _reverseStatIndex() {
    final buf = StringBuffer()
      ..writeln('## Reverse stat index\n')
      ..writeln(
        'One table per `ItemModifiers` field: every item that carries it, '
        'so "what already grants % shield" is one lookup instead of a grep '
        'across five catalogue files.\n',
      )
      ..writeln(
        '⚠️ **Values are the DEF\'s base numbers.** Quality (Rough/Standard/'
        'Ornate/Master) scales every combat stat per-instance at '
        '80/100/120/140% (`ItemModifiers.scaledBy`) — an actual dropped or '
        'crafted item can read higher or lower than the row below.\n',
      );

    final noItemGrants = <String>[];
    for (final (field, getter) in _modifierFields) {
      // ⚠️ Scans the WHOLE catalogue, not one zone — see the doc above.
      final rows = [
        for (final d in ItemCatalogue.all)
          if (_modifiersOf(d) case final m? when getter(m) != 0) d,
      ]..sort(_byZoneThenLevelThenId);

      if (rows.isEmpty) {
        noItemGrants.add(field);
        continue;
      }

      buf.writeln('### `$field`\n');
      buf.writeln('| Name | Id | Value | Slot | Rarity | Equip Lv | Zone |');
      buf.writeln('|---|---|---|---|---|---|---|');
      for (final d in rows) {
        final value = getter(_modifiersOf(d)!);
        final slot = d is EquipmentDef ? d.slot.name : 'gem';
        final zone = ItemCatalogue.zoneOf(d.id) ?? '—';
        buf.writeln(
          '| ${ItemCatalogue.displayName(d)} | `${d.id}` | $value | $slot '
          '| ${d.rarity.name} | ${d.equipLevel} | $zone |',
        );
      }
      buf.writeln();
    }

    // ⚠️ Absence stated explicitly — see the doc above. A field silently
    // missing from the document above reads as "nobody has looked yet"; a
    // field listed here reads as "looked, and nothing grants it (yet)".
    if (noItemGrants.isNotEmpty) {
      buf.writeln('### No item grants\n');
      buf.writeln(noItemGrants.map((f) => '`$f`').join(', '));
      buf.writeln();
    }
    return buf.toString();
  }

  // ---- ordering ---------------------------------------------------------

  /// Zone id → its index in [World.locations] — "the order the campaign
  /// meets them", per that list's own doc comment. Every zone-scoped table
  /// in this file sorts by this first, so regenerating after a new zone
  /// lands only appends rows instead of reshuffling existing ones.
  static final Map<String, int> _zoneOrder = {
    for (var i = 0; i < World.locations.length; i++) World.locations[i].id: i,
  };

  /// ⭐ **Zone order (as shipped), then equip level, then id** — the ordering
  /// the task calls out explicitly, so two regenerations from the same code
  /// diff as empty.
  static int _byZoneThenLevelThenId(ItemDef a, ItemDef b) {
    final za = _zoneOrder[ItemCatalogue.zoneOf(a.id)] ?? 1 << 30;
    final zb = _zoneOrder[ItemCatalogue.zoneOf(b.id)] ?? 1 << 30;
    if (za != zb) return za.compareTo(zb);
    final byLevel = a.equipLevel.compareTo(b.equipLevel);
    return byLevel != 0 ? byLevel : a.id.compareTo(b.id);
  }

  // ---- items by zone ------------------------------------------------------

  static String _kindOf(ItemDef d) => switch (d) {
    EquipmentDef() => 'equipment',
    ConsumableDef() => 'consumable',
    BeltableDef() => 'beltable',
    MaterialDef() => 'material',
    MoteDef() => 'mote',
    ComponentDef() => 'component',
    ToolDef() => 'tool',
    GemDef() => 'gem',
    KeyDef() => 'key',
  };

  /// Every nonzero [ItemModifiers] field on one item, as `field+n` pairs —
  /// the compact form the per-zone item table uses so a row stays one line.
  static String _compactStats(ItemDef d) {
    final m = _modifiersOf(d);
    if (m == null || m.isEmpty) return '';
    final parts = <String>[
      for (final (field, getter) in _modifierFields)
        if (getter(m) case final v when v != 0) '$field ${v > 0 ? '+' : ''}$v',
    ];
    return parts.join(', ');
  }

  /// A bulk mote or material drops from most of a zone's roster, and
  /// spelling out every dropper turns one table cell into the whole
  /// bestiary — this is the readability cap, not a completeness cap:
  /// `content.json`'s `index.itemSources` (built by the exact same walk)
  /// still lists every one.
  static const int _maxDropsShown = 6;

  /// *Where does this item come from* — derived by walking [RecipeBook],
  /// [GatherNodes] and every [Bestiary] drop table, exactly the sources
  /// `ContentExport._index` walks for `itemSources` (never re-typed).
  ///
  /// ⚠️ **Falls back to the literal string `drop`** for anything none of the
  /// three tables claim (per the task brief) — most often a boss unique or a
  /// gate item whose acquisition is still prose in `world.dart`, not yet a
  /// drop table entry. That fallback is a known gap, not a claim the item
  /// truly drops from something; see the report for the list it currently
  /// covers.
  static String _obtainedBy(String itemId) {
    final craftAndGather = <String>[
      for (final r in RecipeBook.all)
        if (r.outputId == itemId) 'craft: `${r.id}`',
      for (final n in GatherNodes.all)
        if (n.yieldsDefId == itemId) 'gather: `${n.id}`',
    ];
    final droppedBy = [
      for (final e in Bestiary.all)
        if (_dropsItem(e.drops, itemId)) e.id,
    ];
    final dropParts = [
      for (final id in droppedBy.take(_maxDropsShown)) 'drop: `$id`',
      if (droppedBy.length > _maxDropsShown)
        '+${droppedBy.length - _maxDropsShown} more (see content.json)',
    ];
    final parts = [...craftAndGather, ...dropParts];
    return parts.isEmpty ? 'drop' : parts.join('; ');
  }

  static bool _dropsItem(DropTable t, String itemId) =>
      t.always.any((d) => d.defId == itemId) ||
      t.main.any((d) => d.defId == itemId) ||
      t.bonus.any((d) => d.defId == itemId);

  static String _itemsByZone() {
    final buf = StringBuffer()..writeln('## Items by zone\n');
    for (final loc in World.locations) {
      final items = ItemCatalogue.byZone[loc.id];
      if (items == null || items.isEmpty) continue;
      final sorted = [...items]
        ..sort((a, b) {
          final byLevel = a.equipLevel.compareTo(b.equipLevel);
          return byLevel != 0 ? byLevel : a.id.compareTo(b.id);
        });

      buf.writeln('### ${loc.name} (`${loc.id}`) — ${sorted.length} items\n');
      buf.writeln(
        '| Id | Name | Kind | Slot | Rarity | Equip Lv | Stats | Obtained |',
      );
      buf.writeln('|---|---|---|---|---|---|---|---|');
      for (final d in sorted) {
        final slot = d is EquipmentDef ? d.slot.name : '';
        buf.writeln(
          '| `${d.id}` | ${ItemCatalogue.displayName(d)} | ${_kindOf(d)} '
          '| $slot | ${d.rarity.name} | ${d.equipLevel} '
          '| ${_compactStats(d)} | ${_obtainedBy(d.id)} |',
        );
      }
      buf.writeln();
    }
    return buf.toString();
  }

  // ---- bestiary by zone ---------------------------------------------------

  static String _notableDrops(EnemyDef e) {
    final names = <String>{
      for (final d in [...e.drops.main, ...e.drops.bonus])
        if (d.defId != null)
          if (ItemCatalogue.tryById(d.defId!) case final def?)
            ItemCatalogue.displayName(def),
    };
    return names.isEmpty ? '—' : names.join(', ');
  }

  static String _bestiaryByZone() {
    final buf = StringBuffer()..writeln('## Bestiary by zone\n');
    for (final loc in World.locations) {
      final creatures = Bestiary.forZone(loc.id);
      if (creatures.isEmpty) continue;
      final sorted = [...creatures]
        ..sort((a, b) {
          final byRank = a.rank.index.compareTo(b.rank.index);
          return byRank != 0 ? byRank : a.id.compareTo(b.id);
        });

      buf.writeln(
        '### ${loc.name} (`${loc.id}`) — ${sorted.length} creatures\n',
      );
      buf.writeln(
        '| Id | Name | Rank | Archetype | Element | Level | HP scale | '
        'Power scale | Notable drops |',
      );
      buf.writeln('|---|---|---|---|---|---|---|---|---|');
      for (final e in sorted) {
        final elements = e.elements.map((el) => el.name).join('/');
        // ⚠️ No per-creature level exists (EnemyDef carries none — a
        // creature scales with the PLAYER'S level, per `maxHpAt`). The
        // zone's enemy band is the closest fact on record, same string the
        // world map already shows via `GameLocation.enemyBandLabel`.
        final level = '${loc.minLevel}-${loc.maxLevel}';
        buf.writeln(
          '| `${e.id}` | ${e.name} | ${e.rank.label} | ${e.archetype.name} '
          '| $elements | $level | ×${e.archetype.hpScale} '
          '| ×${e.archetype.damageScale} | ${_notableDrops(e)} |',
        );
      }
      buf.writeln();
    }
    return buf.toString();
  }

  // ---- recipes by skill ---------------------------------------------------

  static String _formatItem(String defId, int count) {
    final def = ItemCatalogue.tryById(defId);
    final name = def == null ? defId : ItemCatalogue.displayName(def);
    return '${count}x $name';
  }

  static String _recipesBySkill() {
    final buf = StringBuffer()..writeln('## Recipes by skill\n');
    for (final skill in CraftSkill.values) {
      final recipes = RecipeBook.forSkill(skill);
      if (recipes.isEmpty) continue;
      final sorted = [...recipes]
        ..sort((a, b) {
          final byLevel = a.skillLevel.compareTo(b.skillLevel);
          return byLevel != 0 ? byLevel : a.id.compareTo(b.id);
        });

      buf.writeln(
        '### ${Skills.displayName(skill.name)} — ${sorted.length} recipes\n',
      );
      buf.writeln('| Id | Gate | Inputs | Output | XP |');
      buf.writeln('|---|---|---|---|---|');
      for (final r in sorted) {
        final inputs = r.inputs
            .map((i) => _formatItem(i.defId, i.count))
            .join(', ');
        final output = _formatItem(r.outputId, r.outputCount);
        // ⭐ The shipped formula (`Skills.xpForRecipe`), never a re-typed
        // number: total ingredients × (4 + 2 × gate).
        buf.writeln(
          '| `${r.id}` | ${r.skillLevel} | $inputs | $output '
          '| ${Skills.xpForRecipe(r)} |',
        );
      }
      buf.writeln();
    }
    return buf.toString();
  }
}
